---
title: "Study 4: Supplemental analyses"
subtitle: "Luhrmann, Weisman, et al."
output: 
  html_notebook:
    theme: flatly
    toc: true
    toc_float: true
---

In this notebook, we conduct additional analyses for Study 4: Confirmatory work with undergraduates (as discussed in Supplemental Information).

```{r}
source("../../scripts_general/dependencies.R")
source("../../scripts_general/custom_funs.R")
source("../../scripts_general/var_recode_contrast.R")
source("../scripts_s4/s4_var_groups.R")
source("../../scripts_general/data_load.R")
```

```{r}
d4_long <- d4 %>%
  select(p7_ctry, p7_subj, 
         por_score_std, pv_score_std, abs_score_std, dse_score_std, spev_score_std) %>%
  gather(spirit_scale, spirit_score_std, 
         c(dse_score_std, spev_score_std)) %>%
  mutate(spirit_scale = factor(spirit_scale, 
                               levels = c("dse_score_std", "spev_score_std")))

contrasts(d4_long$p7_ctry) <- contrasts_country; contrasts(d4_long$p7_ctry)
contrasts(d4_long$spirit_scale) <- cbind("_spev" = c(-1, 1)); contrasts(d4_long$spirit_scale)
```


# Missing data

```{r}
# by scale, question
d4_byquestion %>%
  filter(question %in% c(s4_var_pv, s4_var_por, s4_var_abs, 
                         s4_var_dse, s4_var_spev, s4_var_hall, 
                         s4_var_para, s4_var_cog, s4_var_ctl)) %>%
  # this question was missing in Thailand:
  filter(!(question == "p7_por_curse.sick" & p7_ctry == "Thailand")) %>%
  count(scale, response) %>%
  mutate(scale = factor(scale, 
                        levels = c("pv_score", "por_score", "abs_score",
                                   "dse_score", "spev_score", "hall_score",
                                   "para_score", "cog_score", "ctl_score"))) %>%
  arrange(scale) %>%
  group_by(scale) %>%
  mutate(prop = n/sum(n)) %>%
  ungroup() %>%
  filter(is.na(response)) %>%
  mutate(prop_round = case_when(prop < 0.005 ~ "<0.01",
                                TRUE ~ format(round(prop, 2), nsmall = 2)))
```

```{r}
# by scale, participant
d4_byquestion %>%
  filter(question %in% c(s4_var_pv, s4_var_por, s4_var_abs, 
                         s4_var_dse, s4_var_spev, s4_var_hall, 
                         s4_var_para, s4_var_cog, s4_var_ctl)) %>%
  # this question was missing in Thailand:
  filter(!(question == "p7_por_curse.sick" & p7_ctry == "Thailand")) %>%
  count(scale, p7_subj, response) %>%
  mutate(scale = factor(scale, 
                        levels = c("pv_score", "por_score", "abs_score",
                                   "dse_score", "spev_score", "hall_score",
                                   "para_score", "cog_score", "ctl_score"))) %>%
  arrange(scale) %>%
  filter(is.na(response)) %>%
  count(scale) %>%
  mutate(prop = n/505,
         prop_round = case_when(prop < 0.005 ~ "<0.01",
                                TRUE ~ format(round(prop, 2), nsmall = 2)))
```

```{r}
# focus on spiritual events scale
d4_byquestion %>%
  filter(question %in% c(s4_var_spev),
         is.na(response)) %>%
  count(p7_ctry, question) %>%
  spread(p7_ctry, n) %>%
  mutate(question = factor(question, levels = s4_var_spev),
         TOTAL = US + Ghana + Thailand + China + Vanuatu,
         TOTAL_prop = TOTAL/505,
         TOTAL_prop_round = case_when(
           TOTAL_prop < 0.005 ~ "<0.01",
           TRUE ~ format(round(TOTAL_prop, 2), nsmall = 2))) %>%
  select(-TOTAL, -TOTAL_prop) %>%
  arrange(question)
```

```{r}
# focus on porosity scale
d4_byquestion %>%
  filter(question %in% c(s4_var_por),
         is.na(response)) %>%
  count(p7_ctry, question) %>%
  spread(p7_ctry, n) %>%
  mutate(question = factor(question, levels = s4_var_por),
         TOTAL = US + Ghana + Thailand + China + Vanuatu,
         TOTAL_prop = TOTAL/505,
         TOTAL_prop_round = case_when(
           TOTAL_prop < 0.005 ~ "<0.01",
           TRUE ~ format(round(TOTAL_prop, 2), nsmall = 2))) %>%
  select(-TOTAL, -TOTAL_prop) %>%
  arrange(question)
```

```{r}
d4_byquestion_raw <- read_csv("../../study4/data/study4_byquestion.csv") %>%
  select(-X1) %>%
  mutate(p7_ctry = factor(p7_ctry, levels = levels_country))

# attention checks
d4_byquestion_raw %>%
  select(p7_ctry, p7_subj, contains("check")) %>%
  gather(question, response, -p7_ctry, -p7_subj) %>%
  count(question, response) %>%
  group_by(question) %>%
  mutate(prop = format(round(n/sum(n), 2), nsmall = 2)) %>%
  ungroup() %>%
  select(-n) %>%
  spread(response, prop)# %>%
  # filter(is.na(response))
```


# Reliability

```{r}
d_alpha_por <- data.frame()
for(i in c(levels(d4$p7_ctry), "ALL")){
  
  # hacky way of omitting p7_por_curse.sick for Thailand because question was missing
  if(i == "Thailand"){
    v <- s4_var_por[s4_var_por != "p7_por_curse.sick"]
  } else {
    v <- s4_var_por
  }
  
  res <- data.frame(country = i, 
                    alpha = alpha_fun(d4_byquestion %>% 
                                        rename(country = p7_ctry) %>% 
                                        spread(question, response), 
                                      which_vars = v,
                                      which_country = i))
  d_alpha_por <- bind_rows(d_alpha_por, res)
  rm(res)
}
```

```{r}
d_alpha_pv <- data.frame()
for(i in c(levels(d4$p7_ctry), "ALL")){
  res <- data.frame(country = i, 
                    alpha = alpha_fun(d4_byquestion %>% 
                                        rename(country = p7_ctry) %>% 
                                        spread(question, response), 
                                      which_vars = s4_var_pv,
                                      which_country = i))
  d_alpha_pv <- bind_rows(d_alpha_pv, res)
  rm(res)
}
```

```{r}
d_alpha_abs <- data.frame()
for(i in c(levels(d4$p7_ctry), "ALL")){
  res <- data.frame(country = i, 
                    alpha = alpha_fun(d4_byquestion %>% 
                                        rename(country = p7_ctry) %>% 
                                        spread(question, response), 
                                      which_vars = s4_var_abs,
                                      which_country = i))
  d_alpha_abs <- bind_rows(d_alpha_abs, res)
  rm(res)
}
```

```{r}
d_alpha_dse <- data.frame()
for(i in c(levels(d4$p7_ctry), "ALL")){
  res <- data.frame(country = i, 
                    alpha = alpha_fun(d4_byquestion %>% 
                                        rename(country = p7_ctry) %>% 
                                        spread(question, response), 
                                      which_vars = s4_var_dse,
                                      which_country = i))
  d_alpha_dse <- bind_rows(d_alpha_dse, res)
  rm(res)
}
```

```{r}
d_alpha_spev <- data.frame()
for(i in c(levels(d4$p7_ctry), "ALL")){
  
  # hacky way of omitting p7_se_voice.out and p7_se_smell for China because sd(.) ~ 0
  if(i == "China"){
    v <- s4_var_spev[!s4_var_spev %in% c("p7_se_voice.out", "p7_se_smell")]
  } else {
    v <- s4_var_spev
  }
  
  res <- data.frame(country = i, 
                    alpha = alpha_fun(d4_byquestion %>% 
                                        rename(country = p7_ctry) %>% 
                                        spread(question, response), 
                                      which_vars = v,
                                      which_country = i))
  d_alpha_spev <- bind_rows(d_alpha_spev, res)
  rm(res)
}
```

```{r}
d_alpha_hall <- data.frame()
for(i in c(levels(d4$p7_ctry), "ALL")){
  res <- data.frame(country = i, 
                    alpha = alpha_fun(d4_byquestion %>% 
                                        rename(country = p7_ctry) %>% 
                                        spread(question, response), 
                                      which_vars = s4_var_hall,
                                      which_country = i))
  d_alpha_hall <- bind_rows(d_alpha_hall, res)
  rm(res)
}
```

```{r}
d_alpha_para <- data.frame()
for(i in c(levels(d4$p7_ctry), "ALL")){
  res <- data.frame(country = i, 
                    alpha = alpha_fun(d4_byquestion %>% 
                                        rename(country = p7_ctry) %>% 
                                        spread(question, response), 
                                      which_vars = s4_var_para,
                                      which_country = i))
  d_alpha_para <- bind_rows(d_alpha_para, res)
  rm(res)
}
```

```{r}
# NOTE: 9 items were reverse-coded BEFORE being entered!
d_alpha_cog <- data.frame()
for(i in c(levels(d4$p7_ctry), "ALL")){
  res <- data.frame(country = i, 
                    alpha = alpha_fun(d4_byquestion %>% 
                                        rename(country = p7_ctry) %>% 
                                        spread(question, response), 
                                      which_vars = s4_var_cog,
                                      which_country = i))
  d_alpha_cog <- bind_rows(d_alpha_cog, res)
  rm(res)
}
```

```{r}
# omitting 9 reverse-coded items
d_alpha_cog_norev <- data.frame()
for(i in c(levels(d4$p7_ctry), "ALL")){
  res <- data.frame(country = i, 
                    alpha = alpha_fun(d4_byquestion %>% 
                                        rename(country = p7_ctry) %>% 
                                        spread(question, response), 
                                      which_vars = s4_var_cog[!s4_var_cog %in% s4_var_cog_rev],
                                      which_country = i))
  d_alpha_cog_norev <- bind_rows(d_alpha_cog_norev, res)
  rm(res)
}
```

```{r}
# NOTE: 4 items were reverse-coded BEFORE being entered!
d_alpha_ctl <- data.frame()
for(i in c(levels(d4$p7_ctry), "ALL")){
  res <- data.frame(country = i, 
                    alpha = alpha_fun(d4_byquestion %>% 
                                        rename(country = p7_ctry) %>% 
                                        spread(question, response), 
                                      which_vars = s4_var_ctl,
                                      which_country = i))
  d_alpha_ctl <- bind_rows(d_alpha_ctl, res)
  rm(res)
}
```

```{r}
# omitting 4 reverse-coded items
d_alpha_ctl_norev <- data.frame()
for(i in c(levels(d4$p7_ctry), "ALL")){
  res <- data.frame(country = i, 
                    alpha = alpha_fun(d4_byquestion %>% 
                                        rename(country = p7_ctry) %>% 
                                        spread(question, response), 
                                      which_vars = s4_var_ctl[!s4_var_ctl %in% s4_var_ctl_rev],
                                      which_country = i))
  d_alpha_ctl_norev <- bind_rows(d_alpha_ctl_norev, res)
  rm(res)
}
```

```{r}
bind_rows(d_alpha_por %>% mutate(scale = "Porosity Scale"),
          d_alpha_pv %>% mutate(scale = "Porosity Vignettes"),
          d_alpha_abs %>% mutate(scale = "Absorption"),
          d_alpha_dse %>% mutate(scale = "Daily Spiritual Experiences"),
          d_alpha_spev %>% mutate(scale = "Spiritual Events"),
          d_alpha_hall %>% mutate(scale = "Hallucinations"),
          d_alpha_para %>% mutate(scale = "Paranormal"),
          d_alpha_cog %>% mutate(scale = "Need for Cognition"),
          d_alpha_cog_norev %>% mutate(scale = "Need for Cognition (no rev.)"),
          d_alpha_ctl %>% mutate(scale = "Sense of Control"),
          d_alpha_ctl_norev %>% mutate(scale = "Sense of Control (no rev.)")) %>%
  select(scale, country, alpha) %>%
  mutate(scale = factor(scale,
                        levels = c("Porosity Vignettes", "Porosity Scale", 
                                   "Absorption", "Daily Spiritual Experiences",
                                   "Spiritual Events", "Hallucinations", 
                                   "Paranormal", 
                                   "Need for Cognition", 
                                   "Need for Cognition (no rev.)", 
                                   "Sense of Control",
                                   "Sense of Control (no rev.)")), 
         country = factor(country, levels = c(levels_country, "ALL"))) %>%
  spread(country, alpha) %>%
  kable(digits = 2) %>%
  kable_styling() %>%
  column_spec(7, bold = T)
```


# Primary analysis, by country

## Daily Spiritual Experiences

```{r}
r1_dse_us <- lm(dse_score_std2 ~ abs_score_std2, 
                 d4 %>% filter(p7_ctry == "US"))
summary(r1_dse_us)
```

```{r}
r1_dse_gh <- lm(dse_score_std2 ~ abs_score_std2, 
                 d4 %>% filter(p7_ctry == "Ghana"))
summary(r1_dse_gh)
```

```{r}
r1_dse_th <- lm(dse_score_std2 ~ abs_score_std2, 
                 d4 %>% filter(p7_ctry == "Thailand"))
summary(r1_dse_th)
```

```{r}
r1_dse_ch <- lm(dse_score_std2 ~ abs_score_std2, 
                 d4 %>% filter(p7_ctry == "China"))
summary(r1_dse_ch)
```

```{r}
r1_dse_vt <- lm(dse_score_std2 ~ abs_score_std2, 
                 d4 %>% filter(p7_ctry == "Vanuatu"))
summary(r1_dse_vt)
```


## Spiritual Events

```{r}
r1_spev_us <- lm(spev_score_std2 ~ abs_score_std2, 
                 d4 %>% filter(p7_ctry == "US"))
summary(r1_spev_us)
```

```{r}
r1_spev_gh <- lm(spev_score_std2 ~ abs_score_std2, 
                 d4 %>% filter(p7_ctry == "Ghana"))
summary(r1_spev_gh)
```

```{r}
r1_spev_th <- lm(spev_score_std2 ~ abs_score_std2, 
                 d4 %>% filter(p7_ctry == "Thailand"))
summary(r1_spev_th)
```

```{r}
r1_spev_ch <- lm(spev_score_std2 ~ abs_score_std2, 
                 d4 %>% filter(p7_ctry == "China"))
summary(r1_spev_ch)
```

```{r}
r1_spev_vt <- lm(spev_score_std2 ~ abs_score_std2, 
                 d4 %>% filter(p7_ctry == "Vanuatu"))
summary(r1_spev_vt)
```

## Model comparison

```{r}
r1_byp7_ctry_df <- rbind(
  summary(r1_dse_us)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(p7_ctry = "US", scale = "Daily Spiritual Experiences"),
  summary(r1_dse_gh)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(p7_ctry = "Ghana", scale = "Daily Spiritual Experiences"),
  summary(r1_dse_th)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(p7_ctry = "Thailand", scale = "Daily Spiritual Experiences"),
  summary(r1_dse_ch)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(p7_ctry = "China", scale = "Daily Spiritual Experiences"),
  summary(r1_dse_vt)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(p7_ctry = "Vanuatu", scale = "Daily Spiritual Experiences"),
  summary(r1_spev_us)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(p7_ctry = "US", scale = "Spiritual Events"),
  summary(r1_spev_gh)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(p7_ctry = "Ghana", scale = "Spiritual Events"),
  summary(r1_spev_th)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(p7_ctry = "Thailand", scale = "Spiritual Events"),
  summary(r1_spev_ch)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(p7_ctry = "China", scale = "Spiritual Events"),
  summary(r1_spev_vt)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(p7_ctry = "Vanuatu", scale = "Spiritual Events")) %>%
  mutate(Parameter = recode_factor(Parameter,
                                   "(Intercept)" = "Intercept",
                                   "abs_score_std2" = "Absorption")) %>%
  rename(β = Estimate, `Std. Error` = Std..Error, t = t.value,
          p = Pr...t.., Country = p7_ctry, Scale = scale)
```

```{r}
r1_byp7_ctry_df %>% filter(Parameter == "Absorption") %>%
  select(Scale, Country, β, `Std. Error`, t, p) %>%
  mutate(signif = case_when(p < 0.001 ~ "***",
                            p < 0.01 ~ "**",
                            p < 0.05 ~ "*",
                            TRUE ~ ""),
         p = case_when(p < 0.001 ~ "<0.001",
                       TRUE ~ format(round(p, 3), nsmall = 3))) %>%
  rename(" " = signif) %>%
  kable(digits = 2, align = c(rep("l", 2), rep("r", 4), "l")) %>%
  kable_styling() %>%
  collapse_rows(1:2)
```

```{r}
r1_byp7_ctry_df %>% 
  filter(Parameter == "Absorption") %>%
  filter(!(Country == "Vanuatu" & Scale == "Daily Spiritual Experiences")) %>%
  group_by(Scale) %>%
  summarise(min_beta = min(β),
            max_beta = max(β),
            min_p = min(p),
            max_p = max(p)) %>%
  mutate_at(vars(contains("min_"), contains("max_")),
            funs(round(., 3)))
```

```{r}
d4 %>% 
  distinct(p7_ctry, p7_subj) %>% 
  count(p7_ctry)
```
