---
title: "Final datasets"
subtitle: "Luhrmann, Weisman, et al."
output: 
  html_notebook:
    theme: flatly
    toc: true
    toc_float: true
---

In this notebook, we create our final datasets for publication.

```{r}
source("./scripts_general/dependencies.R")
source("./scripts_general/custom_funs.R")
source("./scripts_general/var_recode_contrast.R")
source("./study1/scripts_s1/s1_var_groups.R")
source("./study2/scripts_s2/s2_var_groups.R")
source("./study3/scripts_s3/s3_var_groups.R")
source("./study4/scripts_s4/s4_var_groups.R")
```

```{r}
setwd("./study1/analysis/")
source("../../scripts_general/data_load.R")
```

```{r}
# recoded data
d1r <- read_csv("./study1/data/study1r.csv")

d1_final <- d1 %>%
  full_join(d1r %>% 
              select(subject_id, spev_score) %>%
              rename(spev_recoded_score = spev_score)) %>%
  rename(subject_servicesperweek = servicesperweek,
         subject_specialrole = specialrole) %>%
  select(study, country, site, religion, subject_id, researcher, date,
         subject_gender:subject_specialrole, 
         spev_score, spev_recoded_score, pv_score, abs_score) %>%
  distinct()
```

```{r}
# NOTE SWITCH IN STUDY ORDER: study 2 became study 3 and vice versa
d2_demo <- read_csv("./study2/data/d2_demo.csv")

d3_final <- d2 %>%
  left_join(d2_demo) %>%
  rename(subject_id = subj,
         subject_afford = demo_affr,
         subject_religiosity = demo_howr,
         subject_ses = demo_ses,
         subject_tongues = demo_tung,
         subject_church = demo_chur,
         subject_ethnicity = demo_ethn,
         subject_major = demo_maj,
         subject_occupation_parent = demo_pocc,
         subject_religion = demo_rlgn,
         subject_gender = demo_sex,
         subject_age = demo_age) %>%
  select(study, country, subject_id, 
         subject_gender, subject_age, subject_ethnicity, 
         subject_afford, subject_ses, subject_occupation_parent, subject_major,
         subject_religion, subject_religiosity, subject_church, subject_tongues,
         spev_score, dse_score, abs_score) %>%
  mutate(study = "study 3") %>%
  distinct()
```

```{r}
# NOTE SWITCH IN STUDY ORDER: study 2 became study 3 and vice versa
d3_demo <- read_csv("./study3/data/d_demo.csv")

d2_final <- d3 %>%
  left_join(d3_demo) %>%
  # correct duplicate entry by hand
  filter(!(epi_subj == "50807" & is.na(epi_charc))) %>%
  rename(country = epi_ctry,
         religion = epi_sample,
         subject_id = epi_subj,
         spev_score = spirit_score,
         subject_gender = epi_demo_sex,
         subject_age = epi_demo_age,
         subject_education = epi_demo_edu,
         subject_education_text = epi_demo_edu_8_TEXT,
         subject_occupation = epi_demo_occ,
         subject_occupation_parent = epi_demo_pocc,
         subject_ethnicity = epi_demo_ethn,
         subject_religion = epi_demo_rlgn,
         subject_religion_parent = epi_demo_prel,
         subject_church = epi_demo_chur,
         subject_urban_rural = epi_demo_ubru,
         subject_ses = epi_demo_ses_num,
         subject_religiosity = epi_demo_howr_num,
         subject_afford = epi_demo_affr_num,
         subject_tongues1 = epi_demo_tung_num,
         subject_tongues2 = epi_demo_ytng_num,
         order_cb = epi_version,
         interviewer = epi_whoc,
         language = epi_inlang) %>%
  select(study, country, religion, subject_id, 
         order_cb , interviewer, language,
         subject_gender, subject_age, subject_ethnicity, 
         subject_afford, subject_ses, subject_occupation_parent, subject_occupation,
         subject_education, subject_education_text, subject_urban_rural,
         subject_religion, subject_religion_parent,
         subject_religiosity, subject_church, subject_tongues1, subject_tongues2,
         spev_score, por_score) %>%
  mutate(study = "study 2") %>%
  distinct()
```

```{r}
set.seed(1234)
d4_demo <- read_csv("./study4/data/d4_demo.csv") %>%
  mutate(rand = sample(100000, size = nrow(.))) %>%
  group_by(p7_subj) %>%
  # select one of two "batches" of data entry
  top_n(1, rand) %>%
  ungroup() %>%
  select(-rand)

d4_final <- d4 %>%
  left_join(d4_demo) %>%
  mutate(study = gsub("study", "Study", study)) %>%
  rename(subject_id = p7_subj,
         subject_gender = p7_dem_sex,
         subject_age = p7_dem_age,
         subject_occupation_parent = p7_dem_pocc,
         subject_ethnicity = p7_dem_ethnicity,
         subject_urban_rural = p7_dem_rur.urb,
         subject_afford = p7_dem_affrd.basics,
         subject_ses = p7_dem_ses,
         subject_religiosity = p7_dem_how.sprt.relg,
         subject_religion = p7_dem_religion,
         subject_church = p7_dem_church,
         subject_tongues = p7_dem_holy.tung.gif,
         country = p7_ctry) %>%
  select(study, country, subject_id, 
         subject_gender, subject_age, subject_ethnicity, 
         subject_afford, subject_ses, subject_occupation_parent,
         subject_urban_rural,
         subject_religion, subject_religiosity, subject_church, subject_tongues,
         spev_score, dse_score, pv_score, por_score, abs_score,
         hall_score, para_score, cog_score, ctl_score) %>%
  distinct()
```

```{r}
# export csvs
write.csv(d1_final, "./datasets/sense_spirit_study1.csv", row.names = F)
write.csv(d2_final, "./datasets/sense_spirit_study2.csv", row.names = F)
write.csv(d3_final, "./datasets/sense_spirit_study3.csv", row.names = F)
write.csv(d4_final, "./datasets/sense_spirit_study4.csv", row.names = F)
```

# Checks

```{r}
# study 1
d1_final %>% 
  filter(!is.na(spev_score), !is.na(pv_score), !is.na(abs_score)) %>% 
  distinct(subject_id) %>% count()

# study 2 (formerly study 3)
d2_final %>% 
  filter(!is.na(spev_score), !is.na(por_score)) %>%
  distinct(subject_id, .keep_all = T) %>% count(religion)

# study 3 (formerly study 2)
d3_final %>% 
  filter(!is.na(spev_score), !is.na(dse_score), !is.na(abs_score)) %>%
  distinct(subject_id) %>% count()

# study 4
d4_final %>% 
  filter(!is.na(spev_score), !is.na(dse_score), 
         !is.na(pv_score), !is.na(por_score), !is.na(abs_score)) %>% 
  distinct(subject_id) %>% count()
```

```{r}
r1 <- lmer(spev_score ~ pv_score * abs_score + (1 | country/site/religion),
           d1_final %>% mutate_at(vars(ends_with("_score")), funs(scale)))
regtab_fun(r1, por_var = "pv_score", abs_var = "abs_score") %>% regtab_style_fun()
```

```{r}
r2a <- lmer(spev_score ~ por_score + (1 | country/religion),
            d2_final %>% mutate_at(vars(ends_with("_score")), funs(scale)))
regtab_fun(r2a, por_var = "por_score") %>% regtab_style_fun()
```

```{r}
r2b <- lmer(spev_score ~ por_score + (1 | country),
            d2_final %>%
              filter(religion == "charismatic") %>%
              mutate_at(vars(ends_with("_score")), funs(scale)))
regtab_fun(r2b, por_var = "por_score") %>% regtab_style_fun()
```

```{r}
r3a <- lmer(spev_score ~ abs_score + (1 + abs_score || country),
            d3_final %>% mutate_at(vars(ends_with("_score")), funs(scale)))
regtab_fun(r3a, abs_var = "abs_score") %>% regtab_style_fun()
```

```{r}
r3b <- lmer(dse_score ~ abs_score + (1 + abs_score || country),
            d3_final %>% mutate_at(vars(ends_with("_score")), funs(scale)))
regtab_fun(r3b, abs_var = "abs_score") %>% regtab_style_fun()
```

```{r}
r4a <- lmer(spex ~ pv_score * spirit_scale + (1 | country/subject_id),
            d4_final %>% 
              filter(!is.na(spev_score), !is.na(dse_score), 
                     !is.na(pv_score), !is.na(por_score), !is.na(abs_score)) %>%
              mutate_at(vars(ends_with("_score")), funs(scale)) %>%
              gather(spirit_scale, spex, c(spev_score, dse_score)),
            contrasts = list(spirit_scale = "contr.sum"))
regtab_fun(r4a, por_var = "pv_score") %>% regtab_style_fun()
```

```{r}
r4b <- lmer(spex ~ por_score * spirit_scale + (1 | country/subject_id),
            d4_final %>% 
              filter(!is.na(spev_score), !is.na(dse_score), 
                     !is.na(pv_score), !is.na(por_score), !is.na(abs_score)) %>%
              mutate_at(vars(ends_with("_score")), funs(scale)) %>%
              gather(spirit_scale, spex, c(spev_score, dse_score)),
            contrasts = list(spirit_scale = "contr.sum"))
regtab_fun(r4b, por_var = "por_score") %>% regtab_style_fun()
```

```{r}
r4c <- lmer(spex ~ abs_score * spirit_scale + (1 | country/subject_id),
            d4_final %>% 
              filter(!is.na(spev_score), !is.na(dse_score), 
                     !is.na(pv_score), !is.na(por_score), !is.na(abs_score)) %>%
              mutate_at(vars(ends_with("_score")), funs(scale)) %>%
              gather(spirit_scale, spex, c(spev_score, dse_score)),
            contrasts = list(spirit_scale = "contr.sum"))
regtab_fun(r4c, abs_var = "abs_score") %>% regtab_style_fun()
```

```{r}
# r4d_pv_us
# r4d_pv_gh ...

# r4d_por_us ...

# r4d_abs_us ...
```

```{r}
d4_final_r4e <- d4_final %>%
  filter(!is.na(spev_score), !is.na(dse_score),
         !is.na(pv_score), !is.na(por_score), !is.na(abs_score)) %>%
  mutate_at(vars(ends_with("_score")), funs(scale)) %>%
  mutate(country = factor(country, levels = levels_country)) %>%
  gather(predictor, predictor_score, 
         c(pv_score, por_score, abs_score, cog_score, ctl_score)) %>%
  mutate(predictor = factor(predictor))

contrasts(d4_final_r4e$country) <- contrasts_country
contrasts(d4_final_r4e$predictor) <- cbind(a = c(2, -3, -3, 2, 2),
                                           b = c(-2, 0, 0, 1, 1),
                                           c = c(0, 0, 0, 1, -1),
                                           d = c(0, 1, -1, 0, 0))
```

```{r}
r4e_spev <- lm(spev_score ~ predictor_score * predictor * country, d4_final_r4e)
regtab_fun(r4e_spev) %>% regtab_style_fun(row_emph = 11)
```

```{r}
r4e_dse <- lm(dse_score ~ predictor_score * predictor * country, d4_final_r4e)
regtab_fun(r4e_dse) %>% regtab_style_fun(row_emph = 11)
```

```{r}
r4f_pv <- lmer(spex ~ pv_score * abs_score * spirit_scale 
                 + (1 | country/subject_id),
                 d4_final %>% 
              filter(!is.na(spev_score), !is.na(dse_score), 
                     !is.na(pv_score), !is.na(por_score), !is.na(abs_score)) %>%
              mutate_at(vars(ends_with("_score")), funs(scale)) %>%
              gather(spirit_scale, spex, c(spev_score, dse_score)),
            contrasts = list(spirit_scale = "contr.sum"))
regtab_fun(r4f_pv) %>% regtab_style_fun()
```

```{r}
r4f_por <- lmer(spex ~ por_score * abs_score * spirit_scale 
                 + (1 | country/subject_id),
                 d4_final %>% 
              filter(!is.na(spev_score), !is.na(dse_score), 
                     !is.na(pv_score), !is.na(por_score), !is.na(abs_score)) %>%
              mutate_at(vars(ends_with("_score")), funs(scale)) %>%
              gather(spirit_scale, spex, c(spev_score, dse_score)),
            contrasts = list(spirit_scale = "contr.sum"))
regtab_fun(r4f_por) %>% regtab_style_fun()
```

```{r}
r4g_abs <- lm((abs_score/34) ~ country, d4_final); rsquared(r4g_abs)
r4g_pv <- lm((pv_score/3) ~ country, d4_final); rsquared(r4g_pv)
r4g_por <- lm((por_score/3) ~ country, d4_final); rsquared(r4g_por)
```



