---
title: "Study 3: Supplemental analyses"
subtitle: "Luhrmann, Weisman, et al."
output: 
  html_notebook:
    theme: flatly
    toc: true
    toc_float: true
---

In this notebook, we conduct additional analyses for Study 3: Short-form interviews with the general population (as discussed in Supplemental Information).

```{r}
source("../../scripts_general/dependencies.R")
source("../../scripts_general/custom_funs.R")
source("../../scripts_general/var_recode_contrast.R")
source("../scripts_s3/s3_var_groups.R")
source("../../scripts_general/data_load.R")
```


# Missing data

```{r}
# by scale, question
bind_rows(d3_byquestion %>%
            filter(epi_ctry == "US") %>%
            select(epi_subj, s3_var_spex, s3_var_being_us) %>%
            gather(question, response, -epi_subj) %>%
            mutate(scale = "Spiritual Events"),
          d3_byquestion %>%
            filter(epi_ctry == "Ghana") %>%
            select(epi_subj, s3_var_spex, s3_var_being_gh) %>%
            gather(question, response, -epi_subj) %>%
            mutate(scale = "Spiritual Events"),
          d3_byquestion %>%
            filter(epi_ctry == "Thailand") %>%
            select(epi_subj, s3_var_spex, s3_var_being_th) %>%
            gather(question, response, -epi_subj) %>%
            mutate(scale = "Spiritual Events"),
          d3_byquestion %>%
            filter(epi_ctry == "China") %>%
            select(epi_subj, s3_var_spex, s3_var_being_ch) %>%
            gather(question, response, -epi_subj) %>%
            mutate(scale = "Spiritual Events"),
          d3_byquestion %>%
            filter(epi_ctry == "Vanuatu") %>%
            select(epi_subj, s3_var_spex, s3_var_being_vt) %>%
            gather(question, response, -epi_subj) %>%
            mutate(scale = "Spiritual Events"),
          d3_byquestion %>%
            select(epi_subj, s3_var_por, s3_var_other) %>%
            gather(question, response, -epi_subj) %>%
            mutate(scale = case_when(
              question %in% s3_var_por ~ "Porosity Scale",
              question %in% s3_var_other ~ "Other Extraordinary Events"))) %>%
  mutate(scale = factor(scale,
                        levels = c("Porosity Scale", "Spiritual Events",
                                   "Other Extraordinary Events"))) %>%
  count(scale, response) %>%
  group_by(scale) %>%
  mutate(prop = n/sum(n)) %>%
  ungroup() %>%
  filter(is.na(response))
```

```{r}
# by scale, participant
bind_rows(d3_byquestion %>%
            filter(epi_ctry == "US") %>%
            select(epi_subj, s3_var_spex, s3_var_being_us) %>%
            gather(question, response, -epi_subj) %>%
            mutate(scale = "Spiritual Events"),
          d3_byquestion %>%
            filter(epi_ctry == "Ghana") %>%
            select(epi_subj, s3_var_spex, s3_var_being_gh) %>%
            gather(question, response, -epi_subj) %>%
            mutate(scale = "Spiritual Events"),
          d3_byquestion %>%
            filter(epi_ctry == "Thailand") %>%
            select(epi_subj, s3_var_spex, s3_var_being_th) %>%
            gather(question, response, -epi_subj) %>%
            mutate(scale = "Spiritual Events"),
          d3_byquestion %>%
            filter(epi_ctry == "China") %>%
            select(epi_subj, s3_var_spex, s3_var_being_ch) %>%
            gather(question, response, -epi_subj) %>%
            mutate(scale = "Spiritual Events"),
          d3_byquestion %>%
            filter(epi_ctry == "Vanuatu") %>%
            select(epi_subj, s3_var_spex, s3_var_being_vt) %>%
            gather(question, response, -epi_subj) %>%
            mutate(scale = "Spiritual Events"),
          d3_byquestion %>%
            select(epi_subj, s3_var_por, s3_var_other) %>%
            gather(question, response, -epi_subj) %>%
            mutate(scale = case_when(
              question %in% s3_var_por ~ "Porosity Scale",
              question %in% s3_var_other ~ "Other Extraordinary Events"))) %>%
  mutate(scale = factor(scale,
                        levels = c("Porosity Scale", "Spiritual Events",
                                   "Other Extraordinary Events"))) %>%
  count(scale, epi_subj, response) %>%
  filter(is.na(response)) %>%
  count(scale) %>%
  mutate(prop = n/1025)
```


# Reliability

```{r}
d_alpha_por <- data.frame()
for(i in c(levels(d3$epi_ctry), "ALL")) {
  res <- data.frame(epi_ctry = i, 
                    alpha = alpha_fun(d3_byquestion %>% rename(country = epi_ctry), 
                                      which_vars = s3_var_por,
                                      which_country = i))
  d_alpha_por <- bind_rows(d_alpha_por, res)
  rm(res)
}
```

```{r}
d_alpha_spirit <- data.frame()
for (i in levels(d3$epi_ctry)) {
  df <- d3_byquestion %>%
    rename(country = epi_ctry) %>%
    filter(country == i)
  
  df <- df %>% select_if (function(x) {!all(is.na(x))})
  if (i == "Thailand") {df <- df %>% drop_na()}
  
  if (i == "US") {var_spirit <- c(s3_var_spex, s3_var_being_us)}
  if (i == "Ghana") {var_spirit <- c(s3_var_spex, s3_var_being_gh)}
  if (i == "Thailand") {var_spirit <- c(s3_var_spex, s3_var_being_th)}
  if (i == "China") {var_spirit <- c(s3_var_spex, s3_var_being_ch)}
  if (i == "Vanuatu") {var_spirit <- c(s3_var_spex, s3_var_being_vt)}
  
  res <- data.frame(epi_ctry = i, 
                    alpha = alpha_fun(df, 
                                      which_vars = var_spirit,
                                      which_country = i))
  d_alpha_spirit <- bind_rows(d_alpha_spirit, res)
  rm(res, df, var_spirit)
}
```

```{r}
d_alpha_other <- data.frame()
for(i in c(levels(d3$epi_ctry), "ALL")) {
  res <- data.frame(epi_ctry = i, 
                    alpha = alpha_fun(d3_byquestion %>% rename(country = epi_ctry), 
                                      which_vars = s3_var_other,
                                      which_country = i))
  d_alpha_other <- bind_rows(d_alpha_other, res)
  rm(res)
}
```

```{r}
bind_rows(d_alpha_por %>% mutate(scale = "Porosity Scale"),
          d_alpha_spirit %>% mutate(scale = "Spiritual Events"),
          d_alpha_other %>% mutate(scale = "Other Extraordinary Events")) %>%
  select(scale, epi_ctry, alpha) %>%
  mutate(scale = factor(scale,
                        levels = c("Porosity Scale", "Spiritual Events",
                                   "Other Extraordinary Events")), 
         epi_ctry = factor(epi_ctry, levels = c(levels_country, "ALL"))) %>%
  spread(epi_ctry, alpha) %>%
  kable(digits = 2) %>%
  kable_styling() %>%
  column_spec(7, bold = T)
```

# Primary analysis, by country

## All together

```{r}
r1_us <- lmer(spirit_score_std ~ por_score_std2 + (1 | epi_sample), 
              d3 %>% filter(epi_ctry == "US"))
summary(r1_us)
```

```{r}
r1_gh <- lmer(spirit_score_std ~ por_score_std2 + (1 | epi_sample), 
              d3 %>% filter(epi_ctry == "Ghana"))
summary(r1_gh)
```

```{r}
r1_th <- lmer(spirit_score_std ~ por_score_std2 + (1 | epi_sample), 
              d3 %>% filter(epi_ctry == "Thailand"))
summary(r1_th)
```

```{r}
r1_ch <- lmer(spirit_score_std ~ por_score_std2 + (1 | epi_sample), 
              d3 %>% filter(epi_ctry == "China"))
summary(r1_ch)
```

```{r}
r1_vt <- lmer(spirit_score_std ~ por_score_std2 + (1 | epi_sample), 
              d3 %>% filter(epi_ctry == "Vanuatu"))
summary(r1_vt)
```

```{r}
r1_bycountry_df <- rbind(
  summary(r1_us)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(country = "US"),
  summary(r1_gh)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(country = "Ghana"),
  summary(r1_th)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(country = "Thailand"),
  summary(r1_ch)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(country = "China"),
  summary(r1_vt)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(country = "Vanuatu")) %>%
  mutate(Parameter = recode_factor(Parameter,
                                   "(Intercept)" = "Intercept",
                                   "por_score_std2" = "Porosity Scale")) %>%
  rename(β = Estimate, `Std. Error` = Std..Error, t = t.value,
          p = Pr...t.., Country = country)
```

```{r}
r1_bycountry_df %>% filter(Parameter == "Porosity Scale") %>%
  select(Country, β, `Std. Error`, t, p) %>%
  mutate(signif = case_when(p < 0.001 ~ "***",
                            p < 0.01 ~ "**",
                            p < 0.05 ~ "*",
                            TRUE ~ ""),
         p = case_when(p < 0.001 ~ "<0.001",
                       TRUE ~ format(round(p, 3), nsmall = 3))) %>%
  rename(" " = signif) %>%
  kable(digits = 2, align = c(rep("l", 2), rep("r", 4), "l")) %>%
  kable_styling() %>%
  collapse_rows(1)
```

```{r}
r1_bycountry_df %>% 
  filter(Parameter == "Porosity Scale") %>%
  summarise(min_beta = min(β),
            max_beta = max(β),
            min_p = min(p),
            max_p = max(p)) %>%
  mutate_at(vars(contains("min_"), contains("max_")),
            funs(round(., 3)))
```

```{r}
d3 %>% 
  filter(epi_sample == "general population") %>%
  distinct(epi_ctry, epi_subj) %>% 
  count(epi_ctry)
```


## General population

```{r}
r1GP_us <- lm(spirit_score_std2 ~ por_score_std2, 
            d3 %>% filter(epi_ctry == "US", epi_sample == "general population"))
summary(r1GP_us)
```

```{r}
r1GP_gh <- lm(spirit_score_std2 ~ por_score_std2, 
            d3 %>% filter(epi_ctry == "Ghana", epi_sample == "general population"))
summary(r1GP_gh)
```

```{r}
r1GP_th <- lm(spirit_score_std2 ~ por_score_std2, 
            d3 %>% filter(epi_ctry == "Thailand", epi_sample == "general population"))
summary(r1GP_th)
```

```{r}
r1GP_ch <- lm(spirit_score_std2 ~ por_score_std2, 
            d3 %>% filter(epi_ctry == "China", epi_sample == "general population"))
summary(r1GP_ch)
```

```{r}
r1GP_vt <- lm(spirit_score_std2 ~ por_score_std2, 
            d3 %>% filter(epi_ctry == "Vanuatu", epi_sample == "general population"))
summary(r1GP_vt)
```

```{r}
r1GP_bycountry_df <- rbind(
  summary(r1GP_us)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(country = "US"),
  summary(r1GP_gh)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(country = "Ghana"),
  summary(r1GP_th)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(country = "Thailand"),
  summary(r1GP_ch)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(country = "China"),
  summary(r1GP_vt)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(country = "Vanuatu")) %>%
  mutate(Parameter = recode_factor(Parameter,
                                   "(Intercept)" = "Intercept",
                                   "por_score_std2" = "Porosity Scale")) %>%
  rename(β = Estimate, `Std. Error` = Std..Error, t = t.value,
          p = Pr...t.., Country = country)
```

```{r}
r1GP_bycountry_df %>% filter(Parameter == "Porosity Scale") %>%
  select(Country, β, `Std. Error`, t, p) %>%
  mutate(signif = case_when(p < 0.001 ~ "***",
                            p < 0.01 ~ "**",
                            p < 0.05 ~ "*",
                            TRUE ~ ""),
         p = case_when(p < 0.001 ~ "<0.001",
                       TRUE ~ format(round(p, 3), nsmall = 3))) %>%
  rename(" " = signif) %>%
  kable(digits = 2, align = c(rep("l", 2), rep("r", 4), "l")) %>%
  kable_styling() %>%
  collapse_rows(1:2)
```

```{r}
r1GP_bycountry_df %>% 
  filter(Parameter == "Porosity Scale") %>%
  summarise(min_beta = min(β),
            max_beta = max(β),
            min_p = min(p),
            max_p = max(p)) %>%
  mutate_at(vars(contains("min_"), contains("max_")),
            funs(round(., 3)))
```

```{r}
d3 %>% 
  filter(epi_sample == "general population") %>%
  distinct(epi_ctry, epi_subj) %>% 
  count(epi_ctry)
```

## Charismatic Christians

```{r}
r1CC_us <- lm(spirit_score_std2 ~ por_score_std2, 
            d3 %>% filter(epi_ctry == "US", epi_sample == "charismatic"))
summary(r1CC_us)
```

```{r}
r1CC_gh <- lm(spirit_score_std2 ~ por_score_std2, 
            d3 %>% filter(epi_ctry == "Ghana", epi_sample == "charismatic"))
summary(r1CC_gh)
```

```{r}
r1CC_th <- lm(spirit_score_std2 ~ por_score_std2, 
            d3 %>% filter(epi_ctry == "Thailand", epi_sample == "charismatic"))
summary(r1CC_th)
```

```{r}
r1CC_ch <- lm(spirit_score_std2 ~ por_score_std2, 
            d3 %>% filter(epi_ctry == "China", epi_sample == "charismatic"))
summary(r1CC_ch)
```

```{r}
r1CC_vt <- lm(spirit_score_std2 ~ por_score_std2, 
            d3 %>% filter(epi_ctry == "Vanuatu", epi_sample == "charismatic"))
summary(r1CC_vt)
```

```{r}
r1CC_bycountry_df <- rbind(
  summary(r1CC_us)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(country = "US"),
  summary(r1CC_gh)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(country = "Ghana"),
  summary(r1CC_th)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(country = "Thailand"),
  summary(r1CC_ch)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(country = "China"),
  summary(r1CC_vt)$coefficients %>% 
    data.frame() %>% 
    rownames_to_column("Parameter") %>%
    mutate(country = "Vanuatu")) %>%
  mutate(Parameter = recode_factor(Parameter,
                                   "(Intercept)" = "Intercept",
                                   "por_score_std2" = "Porosity Scale")) %>%
  rename(β = Estimate, `Std. Error` = Std..Error, t = t.value,
          p = Pr...t.., Country = country)
```

```{r}
r1CC_bycountry_df %>% filter(Parameter == "Porosity Scale") %>%
  select(Country, β, `Std. Error`, t, p) %>%
  mutate(signif = case_when(p < 0.001 ~ "***",
                            p < 0.01 ~ "**",
                            p < 0.05 ~ "*",
                            TRUE ~ ""),
         p = case_when(p < 0.001 ~ "<0.001",
                       TRUE ~ format(round(p, 3), nsmall = 3))) %>%
  rename(" " = signif) %>%
  kable(digits = 2, align = c(rep("l", 2), rep("r", 4), "l")) %>%
  kable_styling() %>%
  collapse_rows(1:2)
```

```{r}
r1CC_bycountry_df %>% 
  filter(Parameter == "Porosity Scale") %>%
  summarise(min_beta = min(β),
            max_beta = max(β),
            min_p = min(p),
            max_p = max(p)) %>%
  mutate_at(vars(contains("min_"), contains("max_")),
            funs(round(., 3)))
```

```{r}
d3 %>% 
  filter(epi_sample == "charismatic") %>%
  distinct(epi_ctry, epi_subj) %>% 
  count(epi_ctry)
```

