---
title: "Study 3"
subtitle: "Luhrmann, Weisman, et al."
output: 
  html_notebook:
    theme: flatly
    toc: true
    toc_float: true
---

In this notebook, we analyze Study 3: Short-form interviews with the general population.

```{r}
source("../../scripts_general/dependencies.R")
source("../../scripts_general/custom_funs.R")
source("../../scripts_general/var_recode_contrast.R")
source("../scripts_s3/s3_var_groups.R")
source("../../scripts_general/data_load.R")
```

```{r}
# show contrasts
contrasts(d3$epi_ctry)
contrasts(d3$epi_sample)
```


# Demographics

```{r}
# all participants included in dataset
d3 %>% distinct(epi_sample, epi_subj) %>% count(epi_sample)
```

```{r}
# participants missing porosity vignettes score
d3 %>% filter(is.na(por_score_std)) %>% count()

# participants missing spiritual experiences score
d3 %>% filter(is.na(spirit_score_std)) %>% count()

# participants with complete data for primary analysis
d3 %>% filter(!is.na(por_score_std),
              !is.na(spirit_score_std)) %>% count()
```

```{r}
d3_demo <- read_csv("../data/d_demo.csv") %>% select(-X1) %>%
  # correct duplicate entry by hand
  filter(!(epi_subj == "50807" & is.na(epi_charc))) %>%
  distinct()
```

```{r}
d3_demo <- d3_demo %>%
  mutate(male = ifelse(grepl("male", tolower(epi_demo_sex)) &
                         !grepl("female", tolower(epi_demo_sex)), 1, 0),
         female = ifelse(grepl("female", tolower(epi_demo_sex)), 1, 0),
         subject_age = ifelse(epi_demo_age > 120, NA_real_, epi_demo_age),
         # deal with epi_demo_rlgn
         epi_demo_rlgn = case_when(
           epi_demo_rlgn %in% 
             c("7th Day Adventist",
               "A little Catholicism, pray Jesus",
               "Apostolic",
               "Baptist",
               "Catholic",
               "Catholic 5 times a year, don't study bible but large part of family make up.",
               "Catholicism",
               "Christian",
               "Christian Baptist",
               "Christian, raised Catholic",
               "christianity",
               "Christianity",
               "Christianity - possibly Presbyterian / Catholic, Raised Pentecostal",
               "Christianity, nondenominational",
               "Christians",
               "Christiantity",
               "Church of Latter Day Saints",
               "Culturally LDS",
               "Episcopalian",
               "Grew up Catholic",
               "ICGC Cape Coast Branch, Christianity",
               "Jehovah Witness", 
               "Jehovah's Witness",
               "LDS Latter Day Saints",
               "Methodist",
               "non denominational / Christian",
               "non-denominational",
               "Not specific type/denomination, parents bounced around, all Christian",
               "Orthodox Christian", "Pentecostal", "Pentecostal preacher",
               "Personal relationship w/ Jesus Christ", "Presbyterian",
               "Roman Catholic", "SDA (Christianity)",
               "Seventh Day Adventist Church", "True Jesus Church",
               "Unitarian Universalism", "United Methodist") ~ "Christian",
           epi_demo_rlgn %in% 
             c("Actually believe in Buddhism",
               "Buddhism", "Buddhism (believe)",
               "Buddhism / Ancestors (a little bit believe)",
               "Buddhism, incline to deism",
               "Buddhism. Practice and has been vegetarian for 20 years",
               "Buddhist",
               "Buddhist (interviewed @ church)",
               "Incline to Buddhism", "Studying Buddhism",
               "Vipassana Buddhism",
               "Wat Baan Pong Kiang",
               "Wat Hua Deng", 
               "Wat Nong Ban") ~ "Buddhist",
           # epi_demo_rlgn %in% 
           #   c("Family - Orthodox Jew / Jewish",
           #     "Judaism", "Orthodox Jewish") ~ "Jewish",
           epi_demo_rlgn %in%
             c("Islam", 
               "Islam, but not believe anything", 
               "Islamic", 
               "Islamic Religion",
               "Muslim") ~ "Muslim",
           # epi_demo_rlgn %in% 
           #   c("Hinduism") ~ "Hindu",
           grepl("agnost", tolower(epi_demo_rlgn)) |
             grepl("atheis", tolower(epi_demo_rlgn)) |
             grepl("don't", tolower(epi_demo_rlgn)) |
             grepl("none", tolower(epi_demo_rlgn)) |
             tolower(epi_demo_rlgn) %in% 
             c("n/a", "no", 
               tolower("No (ex - JW) Partner Christian - Possibly Korean Baptist"), 
               "no religion", "no religion, finding one", "not really",
               tolower("Religion is a choice; I'm not interested in it.")) ~ "Agnostic/Atheist",
           TRUE ~ "Other"),
         epi_demo_ubru = recode(epi_demo_ubru,
                                "Urban" = 1, "Rural" = 0),
         epi_sample = recode_factor(epi_charc,
                                    "0" = "general pop.",
                                    "1" = "charismatic Chr."),
         agnostic_atheist = (epi_demo_rlgn == "Agnostic/Atheist"),
         buddhist = (epi_demo_rlgn == "Buddhist"),
         christian = (epi_demo_rlgn == "Christian"),
         muslim = (epi_demo_rlgn == "Muslim"),
         other = (epi_demo_rlgn == "Other"))
         # epi_demo_ses_num already coded as -2 to +2
         # epi_demo_howr_num already coded as -2 to +2
         # epi_demo_affr_num already coded as 1 = yes, 0 = no
         # epi_charc already coded as 1 = yes, 0 = no
```

XX BOOKMARK

```{r}
d3_demo %>%
  group_by(epi_ctry, epi_sample) %>%
  summarise(n = n(),
            age_range = paste0(min(subject_age, na.rm = T), "-",
                               max(subject_age, na.rm = T)),
            mean_age = mean(subject_age, na.rm = T),
            percent_male = mean(male, na.rm = T),
            percent_female = mean(female, na.rm = T),
            percent_urban = mean(epi_demo_ubru, na.rm = T),
            percent_affr = mean(epi_demo_affr_num, na.rm = T),
            mean_ses = mean(epi_demo_ses_num, na.rm = T),
            mean_howr = mean(epi_demo_howr_num, na.rm = T),
            percent_christian = mean(christian, na.rm = T),
            percent_agnostic_atheist = mean(agnostic_atheist, na.rm = T),
            percent_buddhist = mean(buddhist, na.rm = T),
            percent_muslim = mean(muslim, na.rm =T),
            percent_other = mean(other, na.rm = T)) %>%
  ungroup() %>%
  # mutate_at(vars(starts_with("mean_")), funs(format(round(., 2), nsmall = 2))) %>%
  mutate_at(vars(starts_with("percent_")),
            funs(paste0(round(. * 100), "%"))) %>%
  rename(Country = epi_ctry, Sample = epi_sample,
         `Age range` = age_range, `Mean age` = mean_age,
         `% male` = percent_male, `% female` = percent_female,
         `% urban` = percent_urban, `% can afford` = percent_affr,
         `Mean SES` = mean_ses, `Mean religiosity` = mean_howr,
         `% Christian` = percent_christian, 
         `% Agnostic/Atheist` = percent_agnostic_atheist, 
         `% Buddhist` = percent_buddhist, 
         `% Muslim` = percent_muslim, 
         `% Other` = percent_other) %>%
  mutate(Country = factor(Country, levels = levels_country)) %>%
  arrange(Country, Sample) %>%
  kable(digits = 2, align = c(rep("l", 2), rep("r", ncol(.) - 2))) %>%
  kable_styling(font_size = 16) # %>%
  # collapse_rows(1:2)
```

# Predicting Spiritual Events

## Attemping to fit more complex random effects structures

```{r}
r1a <- lmer(spirit_score_std ~ por_score_std + 
              (1 + por_score_std | epi_ctry/epi_sample), d3) # failed to converge
r1b <- lmer(spirit_score_std ~ por_score_std + 
              (1 + por_score_std || epi_ctry/epi_sample), d3) # failed to converge
r1c <- lmer(spirit_score_std ~ por_score_std + 
              (1 + por_score_std | epi_ctry), d3) # failed to converge
r1d <- lmer(spirit_score_std ~ por_score_std + 
              (1 + por_score_std || epi_ctry), d3) # failed to converge
r1e <- lmer(spirit_score_std ~ por_score_std + 
              (0 + por_score_std| epi_ctry), d3) # ok, missing random intercepts
r1f <- lmer(spirit_score_std ~ 0 + por_score_std + 
              (1 + por_score_std| epi_ctry/epi_sample), d3) # singular

```


## Primary analysis

```{r}
r1 <- lmer(spirit_score_std ~ por_score_std + 
             (1 | epi_ctry/epi_sample), d3)
summary(r1)
```

```{r}
rsquared(r1)
```

```{r}
regtab_fun(r1, por_name = "Porosity Scale") %>% regtab_style_fun(row_emph = 2)
```

```{r}
regtab_ran_fun(r1, country_var = "epi_ctry", religion_var = "epi_sample") %>% 
  regtab_style_fun()
```

## Bayesian regression

```{r}
# r1_bayes <- brm(spirit_score_std ~ por_score_std +
#                   (1 | epi_ctry/epi_sample), d3,
#                 control = list(adapt_delta = 0.99),
#                 seed = 1234, cores = 4, chains = 4)
# saveRDS(r1_bayes, "./models/r1_bayes.RDS")

r1_bayes <- readRDS("./models/r1_bayes.RDS")

summary(r1_bayes)
```

```{r}
bayes_R2(r1_bayes)
```

```{r}
regtab_fun(r1_bayes, por_name = "Porosity Scale") %>% regtab_style_fun(row_emph = 2)
```

```{r}
regtab_ran_fun(r1_bayes, 
               country_var = "epi_ctry", 
               religion_var = "epi_sample", 
               religion_name = "Sample") %>% 
  regtab_style_fun()
```

## Country and sample as fixed effects

```{r}
r2 <- lm(spirit_score_std ~ por_score_std * epi_ctry * epi_sample, d3) 
summary(r2)
```

```{r}
rsquared(r2)
```

```{r}
regtab_fun(r2, 
           por_name = "Porosity Vignettes", 
           country_var1 = "epi_ctry_gh",
           country_var2 = "epi_ctry_th",
           country_var3 = "epi_ctry_ch",
           country_var4 = "epi_ctry_vt",
           religion_var = "epi_sample_ch",
           religion_name = "Sample (Ch.)") %>% 
  regtab_style_fun(row_emph = 2)
```


# Predicting Other Extraordinary Events

```{r}
r3 <- lmer(other_score_std ~ por_score_std +
             (1 | epi_ctry/epi_sample),
           data = d3)
summary(r3)
```

```{r}
rsquared(r3)
```

```{r}
regtab_fun(r3, por_name = "Porosity Vignettes") %>% regtab_style_fun(row_emph = 2)
```

```{r}
regtab_ran_fun(r3, 
               country_var = "epi_ctry", 
               religion_var = "epi_sample",
               religion_name = "Sample") %>% 
  regtab_style_fun()
```
